- name: Cart configure
  hosts: cart
  become: yes
  tasks:
  - name: Enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y
    
  - name: Install NodeJS
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: Create system user roboshop
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop system user"

  - name: Delete app directory # Befoe creating an app directory, we need to delete it if previously existed.
    ansible.builtin.file:
      path: /app
      state: absent

  - name: Create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Delete cart zip file # Before downloading, we need to delete it if existed.
    ansible.builtin.file:
      path: /tmp/cart.zip
      state: absent

  - name: Download the Cart
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip

  - name: Unarchive the Cart  # Remote machine -> cart
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes # Provide yes if file already existed in the remote machine

  - name: Install dependencies
    community.general.npm:
      path: /app

  - name: Copy cart service
    ansible.builtin.template:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: Daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Start the Cart
    ansible.builtin.service:
      name: cart
      state: restarted
      enabled: yes