- name: Catalogue configure
  hosts: catalogue
  become: yes
  tasks:
  - name: Enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y
    
  - name: Install NodeJS
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: Create system user roboshop
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop system user"

  - name: Delete app directory # Befoe creating an app directory, we need to delete it if previously existed.
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Delete catalogue zip file # Before downloading, we need to delete it if existed.
    ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent

  - name: Download the catalogue
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip

  - name: Unarchive the catalogue  # Remote machine -> catalogue
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes # Provide yes if file already existed in the remote machine

  - name: Install dependencies
    community.general.npm:
      path: /app

  - name: Copy catalogue service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: Copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Install MongoDB client
    ansible.builtin.dnf:
      name: mongodb-mongosh # We can also use package module but dnf is preferable
      state: present

  - name: Check products loaded
    ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: Print the output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: Load the products
    ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
    when: catalogue_output.stdout  | int < 0

  - name: Start the catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes