- name: Mongodb configure
  hosts: mongodb
  become: yes
  tasks:
  - name: Copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo # cp mongo.repo /etc/yum.repos.d/mongo.repo --> equivalent to earlier
  
  - name: Install mongodb server
    ansible.builtin.dnf:
      name: mongodb-org # We can also use package module but dnf is preferable
      state: present

  - name: Allow remote connections
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: Start and enable mongodb
    ansible.builtin.service:
      name: mongod
      enabled: yes
      state: started

  # - name: Restart mongodb
  #   ansible.builtin.service:
  #     name: mongod
  #     state: restarted