- name: Create EC2 instances and R53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-0bdbfe5495a912910
    ami_id: ami-0220d79f3f480ecf5
    env: dev
    instances:
    - mongodb
    - catalogue
  tasks:
  - name: Create EC2 instance
    amazon.aws.ec2_instance:
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      name: "{{ item }}-{{ env }}"
      tags:
        Project: roboshop
        Component: "{{ item }}"
        Environment: "{{ env }}"
        Name: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: Print the output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
